### ISSUE TITLE
[Suggestion] Rotateable text areas/nonrectangular text areas

### ISSUE THREAD

**Issue by lugia19** [xulihang/ImageTrans-docs#14]
Last suggestion, I promise - I figured I'd write down all the improvements I thought of.

It would be very useful if it were possible to rotate or use non-rectangular text areas. There's plenty of cases where text may be slanted and selecting it all using a rectangular text are could lead to it overlapping other text.

**Comment by xulihang** [comment]
This will not be easy to do since it is related to how localization results should be managed.

Currently, the position is saved in a rectangular format: X, Y, width, height.

A new vertices format should be added to support non-rectangular text areas: x1, y1, x2, y2, x3, y3, x4, y4. Also, it should allow users to adjust these vertices as well.

**Comment by lugia19** [comment]
I see, that makes sense. Would it be possible to add an angle value to the position format perhaps? That should at least allow for rotation, which would go a long way. To maintain compatibility with existing project files, you could simply set the value to 0 if it's not present.

**Comment by xulihang** [comment]
Rotation has been enhanced in v1.6.1. Check out this comment for more info: https://github.com/xulihang/ImageTrans-docs/issues/157#issuecomment-1052121718
