### ISSUE TITLE
[Bug] Auto font resize not doing anything

### ISSUE THREAD

**Issue by lugia19** [xulihang/ImageTrans-docs#16]
I have auto font resize enabled, but it doesn't seem to be doing anything - I'm positive it used to work before.
![bug](https://user-images.githubusercontent.com/21088033/112317830-56940b00-8ca4-11eb-9d92-cd0a87ec2b56.png)

**Comment by xulihang** [comment]
This is really a bug. I use a non-public JavaFX API to calculate font size and change the font size according to the width and height of the text area. The bug did not exist until I chose to render TextFlow to image so that changing the percentage will not affect the result. 

I found the AutoSize does not work for some font. I haven't figured the reason.

**Comment by lugia19** [comment]
I see. Well, I hope you manage to fix it.

**Comment by xulihang** [comment]
What font are you using? I can't manage to reproduce this problem now.

**Comment by lugia19** [comment]
I'm using the wildwords font - see attachment (zipped due to github not support .ttf uploads).
[wildwordsroman.zip](https://github.com/xulihang/ImageTrans-docs/files/6197894/wildwordsroman.zip)

**Comment by xulihang** [comment]
All right. I can reproduce this with your English font.

For now, you could manually set the font size after Auto Font Resize (the font still can resize when it is being dragged. Drag to resize and click the text area to update font size in the tool bar). Since there is a local style specifying which size to use, the result will be kept.

![image](https://user-images.githubusercontent.com/5462205/112328411-43f3f300-8cf1-11eb-8083-2c7b3462f077.png)

**Comment by lugia19** [comment]
Something else I found out: if I enter typesetting mode, and click on a textbox, the autoresize will kick in. It goes away once typesetting mode is disabled however.

**Comment by xulihang** [comment]
I found that when a textbox is being added, the resize may fail. It fails to measure the textbox's current text height for some font.

I seem to fix this by resizing the font twice (the second time simulating the drag event).

See the video.

Before:

https://user-images.githubusercontent.com/5462205/112709018-cbf41b80-8ef0-11eb-843d-1833c63466b6.mp4

After:


https://user-images.githubusercontent.com/5462205/112709042-f0e88e80-8ef0-11eb-8404-e331cd58281c.mp4
