### ISSUE TITLE
Exporting to PSD appends NULL in text layer

### ISSUE THREAD

**Issue by aravindnc** [xulihang/ImageTrans-docs#160]
When I tried to export to PSD, All text layers seems to have NULL prepended to it. Any idea what is causing this? Attaching screenshots.

[out.txt](https://github.com/xulihang/ImageTrans-docs/files/8102172/out.txt)
![Screenshot 2022-02-19 180827](https://user-images.githubusercontent.com/495110/154801121-97aadf94-a232-484c-8f69-eda0e2a2ae63.png)

**Comment by xulihang** [comment]
Are you using the javascript version or the au3 exe version (automatically starts photoshop)?

**Comment by aravindnc** [comment]
Sorry not sure about that. Photoshop was already opened, so when I clicked export to psd, it automatically starts running in Photoshop.

**Comment by xulihang** [comment]
I see. This is a bug which can be fixed with this commit: https://github.com/xulihang/ImageTrans_PhotoshopScripts/commit/917e659593a75eb380bb4a7054e9ea5b8555ffe8

You can download the zip of updated files and replace the previous files to fix this.

[scripts_fixed.zip](https://github.com/xulihang/ImageTrans-docs/files/8102242/scripts_fixed.zip)

**Comment by aravindnc** [comment]
Thank you.
