### ISSUE TITLE
Bubble content not removed completely.

### ISSUE THREAD

**Issue by aravindnc** [xulihang/ImageTrans-docs#163]
See the below screenshots, some texts in the bubbles are not getting removed when precise text-removal is selected.

Creating bubbles and test
![image](https://user-images.githubusercontent.com/495110/154803908-d0445182-34c6-4249-a00a-62098a032344.png)

After translation,
![image](https://user-images.githubusercontent.com/495110/154803939-c4cb0812-9782-40cd-ada1-2cf3f7862f92.png)

The issue happens to some bubbles, not everyone. How can we fix this.

**Comment by xulihang** [comment]
1. The text box must cover the entire text.
2. The text mask of some text which has similar depth to the background or is connected to the edge cannot be correctly generated. You can manually edit the mask so that the text can be removed. Check out the docs for details: https://imagetrans.readthedocs.io/en/latest/textarea_detection_and_text_reinjection.html

**Comment by aravindnc** [comment]
Edited mask and worked perfectly. You're awesome!!!
