### ISSUE TITLE
[Suggestion] Global font styles and/or creating projects from a template

### ISSUE THREAD

**Issue by lugia19** [xulihang/ImageTrans-docs#17]
It's very likely someone might reuse the same font styles for multiple projects, so having global font styles would be nice.
Alternatively, a way to easily create new projects based upon a template could also work.

**Comment by xulihang** [comment]
> global style font
Do you mean global font styles across projects?
I am thinking about two ways to reuse them.

1. Save added font styles to a previous added font styles list 
2. Add a font styles setting in Preferences, which is across projects. Users can set which one to use as the default when a new project is created.


As for the template, actually, the Silent Translator uses a template and can generate one from the open project. I am planning to let users use the template in other functions.

Batch Translation and Custom WorkFlow can also have a template so that users don't have to set the parameters every time.

**Comment by lugia19** [comment]
> Do you mean global font styles across projects?

Yes, that's what I meant, I wrote that in a very weird way.
Personally I would suggest method number 2, since it allows the user to manually choose which fonts are available across projects.

**Comment by xulihang** [comment]
Importing font styles from other projects is added in v1.3.5

![image](https://user-images.githubusercontent.com/5462205/112994803-34672500-919d-11eb-81f0-7fb1a6eee47b.png)
