### ISSUE TITLE
Export all pictures to jpg - new feature

### ISSUE THREAD

**Issue by HeLan8** [xulihang/ImageTrans-docs#19]
There is the feature to export the current image to jpg, but when I'm doing custom translations for a volume with 200 pages, it would be easier if I could export all pictures to jpg with one click.

**Comment by xulihang** [comment]
Actually, there is a batch operation available. In Batch -> Generate translated pictures and remember to check the translated checkbox first. But this is broken because of the English localization in the current version. I'll fix this in the next version. You can still perform this by changing the UI to Chinese.

**Comment by HeLan8** [comment]
That explains it, I tried doing that before, but nothing happened. I switched to chinese ui language and works fine now

**Comment by xulihang** [comment]
Fixed in v1.3.4
