### ISSUE TITLE
[Suggestion] Some more hints on how to set up balloon detection

### ISSUE THREAD

**Issue by lugia19** [xulihang/ImageTrans-docs#35]
It would be nice to have some instructions on how to set up balloon detection on azure/baidu in the docs.

**Comment by xulihang** [comment]
The two are very easy to use, I don't think there is need to do this. 

The problem is that they have restrictions. Baidu EasyDL is only available to Chinese and Azure requires a credit card.

**Comment by lugia19** [comment]
I see, I was just confused about the part on the docs that says you have to train your own model.

**Comment by xulihang** [comment]
The two are usable in ImageTrans since it uses the models trained by myself. It is possible for users to train their own models.

As for offline balloon detection, the training using Tensorflow Objection Detection API or Darknet is too complicated. It is a newly added function and I haven't updated the docs.
