### ISSUE TITLE
WEBP support

### ISSUE THREAD

**Issue by annistark** [xulihang/ImageTrans-docs#594]
hello. are you planning to add webp support? or maybe the app already can open webp pictures and I just can't find it.

**Comment by xulihang** [comment]
ImageTrans can convert WebP files. It can convert WebP files pasted or downloaded via Chrome Extension.

But it cannot load WebP files directly. I do not plan to enable importing WebP files into the project since there will be a performance issue. So you have to convert WebP files into JPG or PNG by yourself.
