### ISSUE TITLE
how to merge the text ??

### ISSUE THREAD

**Issue by herrachamp** [xulihang/ImageTrans-docs#60]
![Screenshot 2021-06-13 151519](https://user-images.githubusercontent.com/85825674/121802501-40ba3480-cc5a-11eb-9789-fe4b9cc0b26e.png)

Hi,
I am new here.
I need help in how merge the text in one balloon.
When I export the selected as shown in attachment the output is with line breaks.
And I want it come out as an paragraph.
Is there a way to merge the text for whole pdf automatically.
Because doing it manually taking a lot of time.
Please help me.

**Comment by xulihang** [comment]
The line space in this image is large. You need to increase the minimum height growth in the project settings.

Here:

![image](https://user-images.githubusercontent.com/5462205/121885664-fc589280-cd46-11eb-9a32-543e516a1098.png)

You can make it larger so that the text lines can be merged into one paragraph.

**Comment by herrachamp** [comment]
> The line space in this image is large. You need to increase the minimum growth height in the project settings.
> 
> Here:
> 
> ![image](https://user-images.githubusercontent.com/5462205/121885664-fc589280-cd46-11eb-9a32-543e516a1098.png)
> 
> You can make it larger so that the text lines can be merged into one paragraph.

Thank so much.....
This is what I was looking for....
Thank you very much 😀😀😀😀
